# Site settings
theme = "story"
baseurl = "http://notes.skyletter.cn"
title = "Sky Note Site"
paginate = 5
buildFuture = true

[[menu.social]]
 name = "Twitter"
 title = "fab fa-twitter"
 url = "https://twitter.com/Exp_lo_sion"

[[menu.main]]
  name = "Archives"
  title = "Archives"
  url = "/archives/"

[params]
  author = "Skyletter"
  twitter = "Exp_lo_sion"

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]
